'''
    Author: Turhan Can KARGIN
    Python Version: 3.9.7
    
This forward_velocity_kinematics.py file contains all necessary kinematics functions for the project
'''
#https://www.sciencedirect.com/science/article/pii/S2773186324000082
import numpy as np

# %% Function three_section_planar_robot
def FK_pcc(Kappa, Phi, L): # TODO -> Add if else to figure out when any kappa = 0
    '''
    * Homogeneous transformation matrix 
    * Mapping from configuration parameters to task space for the tip of the continuum robot
    
    Parameters
    ----------
    Kappa : list
        curvature values for all sections.
    Phi : list
        bending angles for all sections
    l : list
        trunk length contains all sections

    Returns
    -------
    T: numpy array
        Transformation matrices containing orientation and position

    '''
    noSeg = len(L)
    T_list = []
    T = 1

    for i in range(noSeg):

        k = Kappa[i]
        l = L[i]
        phi = Phi[i]
        theta = k*l

        cphi = np.cos(phi)
        sphi = np.sin(phi)

        cth = np.cos(theta)
        sth = np.sin(theta)
        
        X = (1-cth)*cphi/k
        Y = (1-cth)*sphi/k
        Z = sth/k

        R11 = cphi**2*cth+sphi**2
        R12 = cphi*sphi*(cth-1)
        R13 = -cphi*sth

        R21 = cphi-sphi-(cth-1)
        R22 = sphi**2*cth+cphi**2
        R23 = -sphi*sth
    
        R31 = cphi*sth
        R32 = sphi*sth
        R33 = cth

        Ti = np.array([R11, R12, R13, 0, R21, R22, R23, 0, R31, R32, R33, 0, X, Y, Z, 1])
        Ti = np.reshape(Ti, (4,4), order="F")

        T_list.append(Ti)

    for i in range(noSeg-1, 0, -1):
        T = T_list[i]*T

    return T

# %% Function three_section_planar_robot
def Jacobian_pcc(delta_kappa, delta_phi, Kappa, Phi, L): # TODO -> figure out singularity
    '''
    * Calculation of jacobian matrix by numerical differentation    

    Parameters
    ----------
    delta_kappa : float
        parameter for numerical differentation. Commonly 0.1
    delta_phi : float
        parameter for numerical differentation. Commonly 0.1
    Kappa : list
        curvature values for all sections.
    Phi : list
        bending angles for all sections
    l : list
        trunk length contains all sections

    Returns
    -------
    J : Numpy array with the shape of (6,6)
        Jacobian Matrix

    '''
    No_q = 2*len(L)
    J = np.zeros((6, No_q))

    for i in range(No_q):
            
        Kappa_p = Kappa.copy() #positive perturbation for kappa
        Phi_p = Phi.copy() #positive perturbation for phi

        Kappa_n = Kappa.copy() #negative perturbation for kappa
        Phi_n = Phi.copy() #negative perturbation for phi

        idx = i//2

        if i%2 == 0:
            Kappa_p[idx] += delta_kappa
            Kappa_n[idx] -= delta_kappa
            epsilon = delta_kappa

        else:
            Phi_p[idx] += delta_phi
            Phi_n[idx] -= delta_phi
            epsilon = delta_phi

        T_p = FK_pcc(Kappa_p, Phi_p, L)
        T_n = FK_pcc(Kappa_n, Phi_n, L)

        Ji_p = (T_p[0:3, 3] - T_n[0:3, 3])/(2*epsilon)
        
        R_p = T_p[0:3, 0:3]
        R_n = T_n[0:3, 0:3]
        R_err = R_p @ R_n.T
        Ji_R = np.array([R_err[2, 1] - R_err[1, 2], R_err[0, 2] - R_err[2, 0], R_err[1, 0] - R_err[0, 1]])/(2*epsilon)        
        
        J[0:3, i] = Ji_p
        J[3:6, i] = Ji_R
    
    return J

# %% Function three_section_planar_robot

# Planar Robot Kinematics Functions
def trans_mat_cc(kappa, l):
    '''
    *  Homogeneous transformation matrix
    *  Mapping from configuration parameters to task space
    * tip frame is aligned so that the x-axis points toward the center of the circle

    Parameters
    ----------
    kappa : list
        curvature value for all sections
    l : list
        trunk length contains all sections

    Returns
    -------
    T: numpy array
        Transformation matrices containing orientation and position

    '''

    # num = sect_points: points per section
    si=np.linspace(0,l, num = 50);
    T= np.zeros((len(si),16));
    
    for i in range(len(si)):
        s=si[i];
        c_ks=np.cos(kappa*s);
        s_ks=np.sin(kappa*s);
        if kappa==0:
            T[i,:] = np.array([c_ks,s_ks,0,0,-s_ks,c_ks,0,0,0,0,1,0,0,s,0,1]);  
        else:
            T[i,:] = np.array([c_ks,s_ks,0,0,-s_ks,c_ks,0,0,0,0,1,0,(c_ks-1)/kappa,s_ks/kappa,0,1]);

    return T

# %% Function three_section_planar_robot
def coupletransformations(T,T_tip):
    '''
    * The forward kinematics for an n section manipulator can then be generated by the product of 
    n matrices. The forward kinematics for our elephant trunk robot with its n sections can be calculated with this function
    * Find orientation and position of distal section (Multiply T of current section with T at tip of previous section)
    

    Parameters
    ----------
    T : np array
        Transformation matrices of current section.
    T_tip : np array
        Transformation at tip of previous section

    Returns
    -------
    Tc : np array
        coupled Transformation matrix

    '''

    Tc=np.zeros((len(T[:,0]),len(T[0,:])));
    for k in range(len(T[:,0])):
        #Tc[k,:].reshape(-1,1)
        p = np.matmul(T_tip,(np.reshape(T[k,:],(4,4),order='F')))
        Tc[k,:] = np.reshape(p,(16,),order='F');
    return Tc


#T = three_section_spatial_robot([2.012, 1.741, 1.01], [0, 0, 0], [0.15, 0.15, 0.15])
T = FK_pcc([2.012, 1.741], [0, 0], [0.15, 0.15])
#J = Jacobian_pcc(0.1, 0.01, [2.012, 1.741, 1.01], [30, 10, -20], [0.15, 0.15, 0.15])
print(T)
#print(J)